version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'cash-track-backend'
      MONGO_INITDB_ROOT_PASSWORD: 'Ctrack5659'

    ports:
      - '27017:27017'
    networks:
      - local

  app:
    depends_on:
      - mongo
    container_name: cash-track-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - '3333:3333'
    networks:
      - local

networks:
  local:
    name: local
